name: deploy application

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      component:
        type: choice
        description: component to deploy. Defaults to 'all'
        default: 'all'
        options: 
        - 'all'
        - 'database'
        - 'application'
      environment:
        type: choice
        description: deployment environment
        options: 
        - 'dev'
        - 'test'
        - 'uat'
        - 'prod'
      release_version:
        type: string
        description: version to be deployed
        required: true
        default: 'latest'
  repository_dispatch:
    branch: main
    types: [automated-deploy-dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.environment }}
  cancel-in-progress: false

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  RC_SRC_PREFIX: ${{ vars.DEPLOYMENT_ARTEFACTS_S3_BUCKET_PREFIX }}
  RC_CPT: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.component ||
    github.event_name == 'repository_dispatch' && github.event.client_payload.component }}
  RC_ENV: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment ||
    github.event_name == 'repository_dispatch' && github.event.client_payload.environment }}
  RC_VER: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.release_version ||
    github.event_name == 'repository_dispatch' && github.event.client_payload.release_version }}

permissions:
  id-token: write

jobs:
  validation:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment ||
      github.event_name == 'repository_dispatch' && github.event.client_payload.environment }}
    outputs:
      version: ${{ steps.verify.outputs.version }}

    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ASSUME_ROLE_NAME }}
          role-session-name: ${{ env.RC_ENV }}-app-deployment-validation
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: validate job parameters
        id: verify
        env:
          RC_SRC: ${{ env.RC_SRC_PREFIX }}-${{ vars.AWS_ACCOUNT_ID }}
        run: |
          get_latest_version() {
            local bucket_name=$1
            local prefix_path=$2

            directories=$(aws s3 ls s3://$bucket_name/$prefix_path/ --summarize --human-readable | grep -E 'PRE|DIR' | awk '{print $2}')
            latest_version=""
            while IFS= read -r dir; do
              version=$(basename "$dir")
              if [[ $version =~ ^[0-9]+(\.[0-9]+){2}$ ]]; then
                if [[ -z $latest_version ]] || (( $(echo "$version" | awk -F '.' '{print $1*10000+$2*100+$3}') > $(echo "$latest_version" | awk -F '.' '{print $1*10000+$2*100+$3}') )); then
                  latest_version=$version
                fi
              fi
            done <<< "$directories"
            echo "$latest_version"
          }

          if [[ $RC_VER == "latest" ]]; then 
            latest_version=$(get_latest_version $RC_SRC 'releases')
            echo """ \
              Executing deploy job using parameters:
                (Application Component) - $RC_CPT
                (Release Version)       - $latest_version (latest)
                (Target Environment)    - $RC_ENV
            """
            echo "version=${latest_version}" >> "$GITHUB_OUTPUT"
          else
            echo """ \
              Executing deploy job using parameters:
                (Application Component) - $RC_CPT
                (Release Version)       - $RC_VER
                (Target Environment)    - $RC_ENV
            """
            echo "version=${RC_VER}" >> "$GITHUB_OUTPUT"
          fi


      - name: validate release candidate version
        env:
          RC_SRC: ${{ env.RC_SRC_PREFIX }}-${{ vars.AWS_ACCOUNT_ID }}
          VERSION: ${{ steps.verify.outputs.version }}
        run: |
          [[ $VERSION =~ ^[0-9]+(\.[0-9]+){2}$ ]] && rc_path="$RC_SRC/releases/$VERSION" || rc_path="$RC_SRC/releases-dev/$VERSION"

          rc_backend_path="$rc_path/backend"
          rc_frontend_path="$rc_path/frontend/$RC_ENV"
          rc_database_path="$rc_path/sql"

          # Database validation
          if [[ $RC_CPT == 'database' || $RC_CPT == 'all' ]]; then
            if [[ `aws s3 ls s3://$rc_database_path|head` ]]; then
              echo "[INFO] Release candidate version [${VERSION}] for component (DATABASE) successfully validated"
            else
              echo "[ERROR] Release candidate version [${VERSION}] does not exist for component (DATABASE). Exiting"
              exit 1
            fi
          fi

          # Application validation
          if [[ $RC_CPT == 'application' || $RC_CPT == 'all' ]]; then
            # Backend
            if [[ `aws s3 ls s3://$rc_backend_path|head` ]]; then
              echo "[INFO] Release candidate version [${VERSION}] for component (BACKEND) successfully validated"
            else
              echo "[ERROR] Release candidate version [${VERSION}] does not exist for component (BACKEND). Exiting"
              exit 1
            fi

            # Frontend
            if [[ `aws s3 ls s3://$rc_frontend_path|head` ]]; then
              echo "[INFO] Release candidate version [${VERSION}] for component (FRONTEND) successfully validated"
            else
              echo "[ERROR] Release candidate version [${VERSION}] does not exist for component (FRONTEND). Exiting"
              exit 1
            fi
          fi

  database:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.component == 'all' || github.event.inputs.component == 'database' ||
      (github.event_name == 'repository_dispatch' && github.event.client_payload.component == 'all') }}
    environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment ||
      github.event_name == 'repository_dispatch' && github.event.client_payload.environment }}
    needs: validation

    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ASSUME_ROLE_NAME }}
          role-session-name: ${{ env.RC_ENV }}-database-deployment
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: deploy database migrations for ${{ env.RC_ENV }}
        env:
          RC_SRC: ${{ env.RC_SRC_PREFIX }}-${{ vars.AWS_ACCOUNT_ID }}
          VERSION: ${{ needs.validation.outputs.version }}
        run: |
          [[ $VERSION =~ ^[0-9]+(\.[0-9]+){2}$ ]] && rc_path="releases" || rc_path="releases-dev"
          lambda_function_name="${RC_ENV}-${{ vars.PROJECT_NAME }}-pg-mutate-lambda"
          cat <<EOF > $GITHUB_WORKSPACE/payload.json
          {
            "type": "run_migrations",
            "authUser": "${{ vars.PROJECT_NAME }}_app_rw",
            "targetDatabase": "${{ vars.PROJECT_NAME }}_db",
            "databaseMigrations": {
              "bucketName": "${RC_SRC}",
              "bucketPrefix": "${rc_path}",
              "releaseVersion": "${VERSION}"
            }
          }
          EOF

          openssl base64 -out $GITHUB_WORKSPACE/encoded_payload.json -in $GITHUB_WORKSPACE/payload.json 
          response=$(aws lambda invoke --function-name $lambda_function_name --region $AWS_REGION --payload file://$GITHUB_WORKSPACE/encoded_payload.json response.txt 2>&1)
          status_code=$(cat response.txt | jq -r '.statusCode')
          status_code=${status_code:-"unset"}
          echo "Status Code is: $status_code"
          if [[ "$status_code" == "500" ]]; then
            echo "[ERROR] Deployment of application component (DATABASE) with version ${VERSION} failed with error:"
            echo "${response}"
            exit 1
          else
            response_payload=$(cat response.txt)
            echo "Response Payload: $response_payload"
            echo "[INFO] Application component (DATABASE) with version ${VERSION} successfully deployed into ${RC_ENV^^}"
          fi

  backend:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.component == 'all' || github.event.inputs.component == 'application' ||
      (github.event_name == 'repository_dispatch' && github.event.client_payload.component == 'all') }}
    environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment ||
      github.event_name == 'repository_dispatch' && github.event.client_payload.environment }}
    needs: validation
    outputs:
      stack-name: ${{ steps.get-stack.outputs.result }}

    steps:
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: setup sam
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ASSUME_ROLE_NAME }}
          role-session-name: ${{ env.RC_ENV }}-backend-app-deployment
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: retrieve backend
        env:
          RC_SRC: ${{ env.RC_SRC_PREFIX }}-${{ vars.AWS_ACCOUNT_ID }}
          VERSION: ${{ needs.validation.outputs.version }}
        run: |
          [[ $VERSION =~ ^[0-9]+(\.[0-9]+){2}$ ]] && rc_path="releases/$VERSION/backend" || rc_path="releases-dev/$VERSION/backend"

          aws s3 cp s3://$RC_SRC/$rc_path/packaged.yml .
          aws s3 cp s3://$RC_SRC/$rc_path/samconfig.yml .
          echo "[INFO] Application component (BACKEND) with version ${VERSION} successfully downloaded"
      
      - name: get stack name
        id: get-stack
        uses: mikefarah/yq@v4.42.1
        with:
          cmd: yq -r '."${{ env.RC_ENV }}".deploy.parameters.stack_name' samconfig.yml

      - name: deploy backend for ${{ env.RC_ENV }}
        env:
          VERSION: ${{ needs.validation.outputs.version }}
        run: |
          sam deploy \
            --template-file packaged.yml \
            --stack-name ${{ steps.get-stack.outputs.result }} \
            --config-env $RC_ENV \
            --region $AWS_REGION \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --role-arn "arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.CF_DEPLOY_ROLE_NAME }}" \
            --tags "BuiltFrom=${VERSION} ProjectName=${{ vars.PROJECT_NAME }} Environment=${RC_ENV}"
          echo "[INFO] Application component (BACKEND) with version ${VERSION} successfully deployed into ${RC_ENV^^}"

  frontend:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.component == 'all' || github.event.inputs.component == 'application' ||
      (github.event_name == 'repository_dispatch' && github.event.client_payload.component == 'all') }}
    environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment ||
      github.event_name == 'repository_dispatch' && github.event.client_payload.environment }}
    needs: 
      - validation
      - backend

    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ASSUME_ROLE_NAME }}
          role-session-name: ${{ env.RC_ENV }}-frontend-app-deployment
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: retrieve frontend for ${{ env.RC_ENV }}
        env:
          RC_SRC: ${{ env.RC_SRC_PREFIX }}-${{ vars.AWS_ACCOUNT_ID }}
          VERSION: ${{ needs.validation.outputs.version }}
        run: |
          [[ $VERSION =~ ^[0-9]+(\.[0-9]+){2}$ ]] && rc_path="releases/$VERSION/frontend/$RC_ENV" || rc_path="releases-dev/$VERSION/frontend/$RC_ENV"

          mkdir build/
          aws s3 cp s3://$RC_SRC/$rc_path/ build/ --recursive
          echo "[INFO] Application component (FRONTEND) with version ${VERSION} successfully downloaded for ${RC_ENV^^}"

      - name: get stack values
        id: get-values
        run: |
          echo "frontend-bucket-name=$( \
            aws cloudformation describe-stacks \
              --stack-name ${{ needs.backend.outputs.stack-name }} \
              --query 'Stacks[0].Outputs[?OutputKey==`FrontendBucketName`].OutputValue' \
              --output text \
          )" >> $GITHUB_OUTPUT
          
          echo "cloudfront-distribution-id=$( \
            aws cloudformation describe-stacks \
              --stack-name ${{ needs.backend.outputs.stack-name }} \
              --query 'Stacks[0].Outputs[?OutputKey==`CloudFrontDistributionId`].OutputValue' \
              --output text \
          )" >> $GITHUB_OUTPUT
      
      - name: clear frontend for ${{ env.RC_ENV }}
        run: |
          aws s3 rm ${{ steps.get-values.outputs.frontend-bucket-name }} --recursive
          echo "[INFO] S3 Bucket for application component (FRONTEND) successfully cleared for ${RC_ENV^^}"

      - name: invalidate cloudfront cache for ${{ env.RC_ENV }}
        run: |
          echo "[INFO] Executing invalidation against CloudFront Distribution Id ${{ steps.get-values.outputs.cloudfront-distribution-id }}"
          invalidation_id=$(aws cloudfront create-invalidation --distribution-id ${{ steps.get-values.outputs.cloudfront-distribution-id }} --paths '/*' --output json \
            | jq -r '.Invalidation.Id')
          
          echo "[INFO] Waiting for invalidation to complete..."
          aws cloudfront wait invalidation-completed --distribution-id ${{ steps.get-values.outputs.cloudfront-distribution-id }} --id $invalidation_id

          if [ $? -eq 0 ]; then
            echo "[INFO] CloudFront cache for application in ${RC_ENV^^} was successfully invalidated"
          elif [ $? -eq 255 ]; then
            echo "[WARN] CloudFront cache for application in ${RC_ENV^^} could not be invalidated"
          fi
        continue-on-error: true

      - name: deploy frontend for ${{ env.RC_ENV }}
        env:
          VERSION: ${{ needs.validation.outputs.version }}
        run: |
          aws s3 cp build/ ${{ steps.get-values.outputs.frontend-bucket-name }} --recursive
          echo "[INFO] Application component (FRONTEND) with version ${RC_VER} successfully deployed for ${RC_ENV^^}"
